spring:
  datasource:
    url: jdbc:mysql://192.168.179.1/taobao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.17.128:2181
  protocol:
    port: -1
    name: dubbo