spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://192.168.17.128:2181
  consumer:
    check: false
    timeout: 10000
    retries: 0
logging:
  config: classpath:log4j2-sit.xml